"""create subclips and subclipsets

Revision ID: 02b4e6607924
Revises: 7910e3e82619
Create Date: 2020-04-17 14:52:19.876523

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02b4e6607924'
down_revision = '7910e3e82619'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subclipsets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subclipsets')),
    sa.UniqueConstraint('name', name=op.f('uq_subclipsets_name'))
    )
    op.create_table('subclips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clip_id', sa.Integer(), nullable=True),
    sa.Column('start_idx', sa.Integer(), nullable=True),
    sa.Column('end_idx', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['clip_id'], ['clips.id'], name=op.f('fk_subclips_clip_id_clips')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subclips'))
    )
    with op.batch_alter_table('subclips', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subclips_clip_id'), ['clip_id'], unique=False)

    op.create_table('subclipset_association',
    sa.Column('subclip_id', sa.Integer(), nullable=True),
    sa.Column('subclipset_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['subclip_id'], ['subclips.id'], name=op.f('fk_subclipset_association_subclip_id_subclips')),
    sa.ForeignKeyConstraint(['subclipset_id'], ['subclipsets.id'], name=op.f('fk_subclipset_association_subclipset_id_subclipsets'))
    )
    with op.batch_alter_table('subclipset_association', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subclipset_association_subclip_id'), ['subclip_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_subclipset_association_subclipset_id'), ['subclipset_id'], unique=False)
        batch_op.create_index('subclipset_joint_idx', ['subclip_id', 'subclipset_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subclipset_association', schema=None) as batch_op:
        batch_op.drop_index('subclipset_joint_idx')
        batch_op.drop_index(batch_op.f('ix_subclipset_association_subclipset_id'))
        batch_op.drop_index(batch_op.f('ix_subclipset_association_subclip_id'))

    op.drop_table('subclipset_association')
    with op.batch_alter_table('subclips', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subclips_clip_id'))

    op.drop_table('subclips')
    op.drop_table('subclipsets')
    # ### end Alembic commands ###
