"""add clip frame path to Image

Revision ID: 09e2d2845329
Revises: 967b7d9a0d73
Create Date: 2019-09-25 17:04:15.104824

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09e2d2845329'
down_revision = '967b7d9a0d73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('clip_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('frame_num', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('path', sa.String(), nullable=True))
        batch_op.create_foreign_key('clip_ids', 'clips', ['clip_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.drop_constraint('clip_ids', type_='foreignkey')
        batch_op.drop_column('path')
        batch_op.drop_column('frame_num')
        batch_op.drop_column('clip_id')

    # ### end Alembic commands ###
