"""add illumination to images

Revision ID: 0d5e829f7a30
Revises: ff5dd5c51ca2
Create Date: 2020-02-14 10:37:29.732537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d5e829f7a30'
down_revision = 'ff5dd5c51ca2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('illumination', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.drop_column('illumination')

    # ### end Alembic commands ###
