"""added smoothers table

Revision ID: 101e08674849
Revises: 02b4e6607924
Create Date: 2020-04-25 17:57:28.592317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '101e08674849'
down_revision = '02b4e6607924'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('smoothers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('smoother_type', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_smoothers')),
    sa.UniqueConstraint('name', name=op.f('uq_smoothers_name'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('smoothers')
    # ### end Alembic commands ###
