"""add landmarkset_id to models

Revision ID: 1939c5c8507f
Revises: 81261cabb991
Create Date: 2020-05-21 11:02:37.546061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1939c5c8507f'
down_revision = '81261cabb991'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('models', schema=None) as batch_op:
        batch_op.add_column(sa.Column('landmarkset_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_models_landmarkset_id'), ['landmarkset_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_models_landmarkset_id_landmarksets'), 'landmarksets', ['landmarkset_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('models', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_models_landmarkset_id_landmarksets'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_models_landmarkset_id'))
        batch_op.drop_column('landmarkset_id')

    # ### end Alembic commands ###
