"""add cols to model

Revision ID: 195e0334edef
Revises: 5645d050683f
Create Date: 2019-09-30 15:32:30.726232

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '195e0334edef'
down_revision = '5645d050683f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('models', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imageset_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('path', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('trained', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('type', sa.String(), nullable=True))
        batch_op.create_index(batch_op.f('ix_models_imageset_id'), ['imageset_id'], unique=False)
        batch_op.create_foreign_key('model_imageset_id', 'imagesets', ['imageset_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('models', schema=None) as batch_op:
        batch_op.drop_constraint('model_imageset_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_models_imageset_id'))
        batch_op.drop_column('type')
        batch_op.drop_column('trained')
        batch_op.drop_column('path')
        batch_op.drop_column('name')
        batch_op.drop_column('imageset_id')

    # ### end Alembic commands ###
