"""add optimize_scale_image

Revision ID: 1cbb610785d5
Revises: ff3f9047edc5
Create Date: 2021-09-23 18:43:02.566643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1cbb610785d5'
down_revision = 'ff3f9047edc5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('models', schema=None) as batch_op:
        batch_op.add_column(sa.Column('optimize_scale_image', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('models', schema=None) as batch_op:
        batch_op.drop_column('optimize_scale_image')

    # ### end Alembic commands ###
