"""imageset

Revision ID: 1e0dfd5a6902
Revises: c68c6764ab57
Create Date: 2019-09-26 17:18:38.552795

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e0dfd5a6902'
down_revision = 'c68c6764ab57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('imageset_association',
    sa.Column('image_id', sa.Integer(), nullable=True),
    sa.Column('imageset_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['image_id'], ['images.id'], ),
    sa.ForeignKeyConstraint(['imageset_id'], ['imagesets.id'], )
    )
    with op.batch_alter_table('imagesets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(), nullable=True))
        batch_op.create_unique_constraint('imageset_name_unique', ['name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('imagesets', schema=None) as batch_op:
        batch_op.drop_constraint('imageset_name_unique', type_='unique')
        batch_op.drop_column('name')

    op.drop_table('imageset_association')
    # ### end Alembic commands ###
