"""create reconstruction tables

Revision ID: 24f7131392db
Revises: 91533fc1b2c8
Create Date: 2021-02-17 03:41:43.022653

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24f7131392db'
down_revision = '91533fc1b2c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('charuco_boards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('number_rows', sa.Integer(), nullable=True),
    sa.Column('number_cols', sa.Integer(), nullable=True),
    sa.Column('square_length', sa.Float(), nullable=True),
    sa.Column('marker_length', sa.Float(), nullable=True),
    sa.Column('marker_bits', sa.Integer(), nullable=True),
    sa.Column('dict_size', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_charuco_boards'))
    )
    op.create_table('calibrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('path', sa.String(), nullable=True),
    sa.Column('charuco_board_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['charuco_board_id'], ['charuco_boards.id'], name=op.f('fk_calibrations_charuco_board_id_charuco_boards')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_calibrations'))
    )
    op.create_table('calibration_videos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(), nullable=True),
    sa.Column('camera_index', sa.Integer(), nullable=True),
    sa.Column('calibration_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['calibration_id'], ['calibrations.id'], name=op.f('fk_calibration_videos_calibration_id_calibrations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_calibration_videos'))
    )
    op.create_table('reconstructions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('calibration_id', sa.Integer(), nullable=True),
    sa.Column('clipgroupset_id', sa.Integer(), nullable=True),
    sa.Column('labelset_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['calibration_id'], ['calibrations.id'], name=op.f('fk_reconstructions_calibration_id_calibrations')),
    sa.ForeignKeyConstraint(['clipgroupset_id'], ['clipgroupsets.id'], name=op.f('fk_reconstructions_clipgroupset_id_clipgroupsets')),
    sa.ForeignKeyConstraint(['labelset_id'], ['labelsets.id'], name=op.f('fk_reconstructions_labelset_id_labelsets')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reconstructions'))
    )
    op.create_table('points',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('x', sa.Float(), nullable=True),
    sa.Column('y', sa.Float(), nullable=True),
    sa.Column('z', sa.Float(), nullable=True),
    sa.Column('reconstruction_id', sa.Integer(), nullable=True),
    sa.Column('clip_group_id', sa.Integer(), nullable=True),
    sa.Column('frame_num', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['clip_group_id'], ['clip_groups.id'], name=op.f('fk_points_clip_group_id_clip_groups')),
    sa.ForeignKeyConstraint(['reconstruction_id'], ['reconstructions.id'], name=op.f('fk_points_reconstruction_id_reconstructions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_points'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('points')
    op.drop_table('reconstructions')
    op.drop_table('calibration_videos')
    op.drop_table('calibrations')
    op.drop_table('charuco_boards')
    # ### end Alembic commands ###
