"""create cnn_smoothers

Revision ID: 2943ffc01926
Revises: 1be18c0808d0
Create Date: 2020-06-25 23:15:46.131741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2943ffc01926'
down_revision = '1be18c0808d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cnn_smoothers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(), nullable=True),
    sa.Column('smoothing_factor', sa.Float(), nullable=True),
    sa.Column('anomaly_threshold', sa.Float(), nullable=True),
    sa.Column('block_length', sa.Integer(), nullable=True),
    sa.Column('scale_factor', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['smoothers.id'], name=op.f('fk_cnn_smoothers_id_smoothers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cnn_smoothers'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cnn_smoothers')
    # ### end Alembic commands ###
