"""add name to ClipSet

Revision ID: 301820016ce6
Revises: 55efb2ec50ed
Create Date: 2019-09-24 13:06:58.572501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '301820016ce6'
down_revision = '55efb2ec50ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clipsets', sa.Column('name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clipsets', 'name')
    # ### end Alembic commands ###
