"""create label_sources

Revision ID: 48d666940917
Revises: 3fb29eacd3d1
Create Date: 2019-10-17 15:36:29.204934

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48d666940917'
down_revision = '3fb29eacd3d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('label_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_label_sources'))
    )
    with op.batch_alter_table('clipsets', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_clipsets_name'), ['name'])
        batch_op.drop_constraint('clipset_name_unique', type_='unique')

    with op.batch_alter_table('dye_detectors', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_dye_detectors_id_label_sources'), 'label_sources', ['id'], ['id'])

    with op.batch_alter_table('imagesets', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_imagesets_name'), ['name'])
        batch_op.drop_constraint('imageset_name_unique', type_='unique')

    with op.batch_alter_table('labels', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_labels_source_id'), ['source_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_labels_source_id_label_sources'), 'label_sources', ['source_id'], ['id'])

    with op.batch_alter_table('models', schema=None) as batch_op:
        batch_op.add_column(sa.Column('training_set_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_models_training_set_id'), ['training_set_id'], unique=False)
        batch_op.create_unique_constraint(batch_op.f('uq_models_name'), ['name'])
        batch_op.drop_index('ix_models_imageset_id')
        batch_op.drop_constraint('model_imageset_id', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_models_training_set_id_imagesets'), 'imagesets', ['training_set_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_models_id_label_sources'), 'label_sources', ['id'], ['id'])
        batch_op.drop_column('imageset_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('models', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imageset_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_models_id_label_sources'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_models_training_set_id_imagesets'), type_='foreignkey')
        batch_op.create_foreign_key('model_imageset_id', 'imagesets', ['imageset_id'], ['id'])
        batch_op.create_index('ix_models_imageset_id', ['imageset_id'], unique=False)
        batch_op.drop_constraint(batch_op.f('uq_models_name'), type_='unique')
        batch_op.drop_index(batch_op.f('ix_models_training_set_id'))
        batch_op.drop_column('training_set_id')

    with op.batch_alter_table('labels', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_labels_source_id_label_sources'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_labels_source_id'))
        batch_op.drop_column('source_id')

    with op.batch_alter_table('imagesets', schema=None) as batch_op:
        batch_op.create_unique_constraint('imageset_name_unique', ['name'])
        batch_op.drop_constraint(batch_op.f('uq_imagesets_name'), type_='unique')

    with op.batch_alter_table('dye_detectors', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_dye_detectors_id_label_sources'), type_='foreignkey')

    with op.batch_alter_table('clipsets', schema=None) as batch_op:
        batch_op.create_unique_constraint('clipset_name_unique', ['name'])
        batch_op.drop_constraint(batch_op.f('uq_clipsets_name'), type_='unique')

    op.drop_table('label_sources')
    # ### end Alembic commands ###
