"""add color_type to clips

Revision ID: 4c7a8b13eae6
Revises: 0d5e829f7a30
Create Date: 2020-03-10 14:15:48.391059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c7a8b13eae6'
down_revision = '0d5e829f7a30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clips', schema=None) as batch_op:
        batch_op.add_column(sa.Column('color_type', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clips', schema=None) as batch_op:
        batch_op.drop_column('color_type')

    # ### end Alembic commands ###
