"""add foreign key indexes

Revision ID: 5645d050683f
Revises: 1e0dfd5a6902
Create Date: 2019-09-28 11:34:15.287905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5645d050683f'
down_revision = '1e0dfd5a6902'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clipset_association', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clipset_association_clip_id'), ['clip_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_clipset_association_clipset_id'), ['clipset_id'], unique=False)

    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_images_clip_id'), ['clip_id'], unique=False)

    with op.batch_alter_table('imageset_association', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_imageset_association_image_id'), ['image_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_imageset_association_imageset_id'), ['imageset_id'], unique=False)

    with op.batch_alter_table('labels', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_labels_image_id'), ['image_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('labels', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_labels_image_id'))

    with op.batch_alter_table('imageset_association', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_imageset_association_imageset_id'))
        batch_op.drop_index(batch_op.f('ix_imageset_association_image_id'))

    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_images_clip_id'))

    with op.batch_alter_table('clipset_association', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clipset_association_clipset_id'))
        batch_op.drop_index(batch_op.f('ix_clipset_association_clip_id'))

    # ### end Alembic commands ###
