"""create_bounding_boxes

Revision ID: 564ca176dd4b
Revises: d4fa38417b7a
Create Date: 2022-03-12 02:38:19.146229

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '564ca176dd4b'
down_revision = 'd4fa38417b7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bounding_boxes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_id', sa.Integer(), nullable=True),
    sa.Column('annotator_id', sa.Integer(), nullable=True),
    sa.Column('x', sa.Integer(), nullable=True),
    sa.Column('y', sa.Integer(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['annotator_id'], ['annotators.id'], name=op.f('fk_bounding_boxes_annotator_id_annotators')),
    sa.ForeignKeyConstraint(['image_id'], ['images.id'], name=op.f('fk_bounding_boxes_image_id_images')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bounding_boxes'))
    )
    with op.batch_alter_table('bounding_boxes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bounding_boxes_image_id'), ['image_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bounding_boxes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bounding_boxes_image_id'))

    op.drop_table('bounding_boxes')
    # ### end Alembic commands ###
