"""add uv_first to clips

Revision ID: 585a7ba2387c
Revises: 83b3dbbab962
Create Date: 2020-08-31 18:56:59.151460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '585a7ba2387c'
down_revision = '83b3dbbab962'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clips', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uv_first', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clips', schema=None) as batch_op:
        batch_op.drop_column('uv_first')

    # ### end Alembic commands ###
