"""sqlite to postgres

Revision ID: 69e4c6782569
Revises: 0f46fe20afc2
Create Date: 2020-12-22 11:49:00.323837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69e4c6782569'
down_revision = '0f46fe20afc2'
branch_labels = ('postgres',) 
depends_on = None


def upgrade():
    pass
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade():
    pass
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
