"""add imageset joint index

Revision ID: 7500d308ff19
Revises: a3cdf85c7666
Create Date: 2020-04-08 14:08:30.528480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7500d308ff19'
down_revision = 'a3cdf85c7666'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('imageset_association', schema=None) as batch_op:
        batch_op.create_index('imageset_joint_idx', ['image_id', 'imageset_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('imageset_association', schema=None) as batch_op:
        batch_op.drop_index('imageset_joint_idx')

    # ### end Alembic commands ###
