"""add light_index to image

Revision ID: 7910e3e82619
Revises: a3a67d9661cb
Create Date: 2020-04-08 21:27:26.456370

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7910e3e82619'
down_revision = 'a3a67d9661cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('light_index', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.drop_column('light_index')

    # ### end Alembic commands ###
