"""added smoothed label sources

Revision ID: 831e6d04e23c
Revises: 8a3b5ca2e618
Create Date: 2020-04-25 18:28:49.641953

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '831e6d04e23c'
down_revision = '8a3b5ca2e618'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('smoothed_label_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('smoother_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['label_sources.id'], name=op.f('fk_smoothed_label_sources_id_label_sources')),
    sa.ForeignKeyConstraint(['smoother_id'], ['smoothers.id'], name=op.f('fk_smoothed_label_sources_smoother_id_smoothers')),
    sa.ForeignKeyConstraint(['source_id'], ['label_sources.id'], name=op.f('fk_smoothed_label_sources_source_id_label_sources')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_smoothed_label_sources'))
    )
    with op.batch_alter_table('smoothed_label_sources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_smoothed_label_sources_smoother_id'), ['smoother_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_smoothed_label_sources_source_id'), ['source_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('smoothed_label_sources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_smoothed_label_sources_source_id'))
        batch_op.drop_index(batch_op.f('ix_smoothed_label_sources_smoother_id'))

    op.drop_table('smoothed_label_sources')
    # ### end Alembic commands ###
