"""added adj mean smoothers table

Revision ID: 8a3b5ca2e618
Revises: 101e08674849
Create Date: 2020-04-25 17:58:03.929293

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a3b5ca2e618'
down_revision = '101e08674849'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adj_mean_smoothers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tp_threshold', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['smoothers.id'], name=op.f('fk_adj_mean_smoothers_id_smoothers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_adj_mean_smoothers'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('adj_mean_smoothers')
    # ### end Alembic commands ###
