"""add frame_rate to clip

Revision ID: 8d93f3862f77
Revises: 65c7ab0906be
Create Date: 2020-08-28 19:34:20.212832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d93f3862f77'
down_revision = '65c7ab0906be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clips', schema=None) as batch_op:
        batch_op.add_column(sa.Column('frame_rate', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clips', schema=None) as batch_op:
        batch_op.drop_column('frame_rate')

    # ### end Alembic commands ###
