"""create corrected_labelsources

Revision ID: 91533fc1b2c8
Revises: 69e4c6782569
Create Date: 2021-02-11 19:23:14.800991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91533fc1b2c8'
down_revision = '69e4c6782569'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('corrected_label_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('original_source_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['label_sources.id'], name=op.f('fk_corrected_label_sources_id_label_sources')),
    sa.ForeignKeyConstraint(['original_source_id'], ['label_sources.id'], name=op.f('fk_corrected_label_sources_original_source_id_label_sources')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_corrected_label_sources'))
    )
    with op.batch_alter_table('corrected_label_sources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_corrected_label_sources_original_source_id'), ['original_source_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('corrected_label_sources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_corrected_label_sources_original_source_id'))

    op.drop_table('corrected_label_sources')
    # ### end Alembic commands ###
