"""add make ClipSet name unique

Revision ID: 93bce01d0351
Revises: 301820016ce6
Create Date: 2019-09-24 13:16:05.924474

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93bce01d0351'
down_revision = '301820016ce6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clipsets', schema=None) as batch_op:
        batch_op.create_unique_constraint('clipset_name_unique', ['name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clipsets', schema=None) as batch_op:
        batch_op.drop_constraint('clipset_name_unique', type_='unique')

    # ### end Alembic commands ###
