"""create clipgroupsets

Revision ID: 956286858f19
Revises: b7d8736e0043
Create Date: 2020-06-05 23:44:17.578271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '956286858f19'
down_revision = 'b7d8736e0043'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clipgroupsets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_clipgroupsets'))
    )
    op.create_table('clipgroupset_association',
    sa.Column('clipgroup_id', sa.Integer(), nullable=True),
    sa.Column('clipgroupset_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['clipgroup_id'], ['clip_groups.id'], name=op.f('fk_clipgroupset_association_clipgroup_id_clip_groups')),
    sa.ForeignKeyConstraint(['clipgroupset_id'], ['clipgroupsets.id'], name=op.f('fk_clipgroupset_association_clipgroupset_id_clipgroupsets'))
    )
    with op.batch_alter_table('clipgroupset_association', schema=None) as batch_op:
        batch_op.create_index('clipgroupset_joint_idx', ['clipgroup_id', 'clipgroupset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_clipgroupset_association_clipgroup_id'), ['clipgroup_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_clipgroupset_association_clipgroupset_id'), ['clipgroupset_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clipgroupset_association', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clipgroupset_association_clipgroupset_id'))
        batch_op.drop_index(batch_op.f('ix_clipgroupset_association_clipgroup_id'))
        batch_op.drop_index('clipgroupset_joint_idx')

    op.drop_table('clipgroupset_association')
    op.drop_table('clipgroupsets')
    # ### end Alembic commands ###
