"""Create clipset_association

Revision ID: 967b7d9a0d73
Revises: 93bce01d0351
Create Date: 2019-09-24 16:42:45.207739

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '967b7d9a0d73'
down_revision = '93bce01d0351'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clipset_association',
    sa.Column('clip_id', sa.Integer(), nullable=True),
    sa.Column('clipset_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['clip_id'], ['clips.id'], ),
    sa.ForeignKeyConstraint(['clipset_id'], ['clipsets.id'], )
    )
    with op.batch_alter_table('clips', schema=None) as batch_op:
        batch_op.add_column(sa.Column('path', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clips', schema=None) as batch_op:
        batch_op.drop_column('path')

    op.drop_table('clipset_association')
    # ### end Alembic commands ###
