"""add index to labelset

Revision ID: a3cdf85c7666
Revises: a413c04cbe20
Create Date: 2020-04-08 14:02:27.852265

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3cdf85c7666'
down_revision = 'a413c04cbe20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('labelset_association', schema=None) as batch_op:
        batch_op.create_index('labelset_joint_idx', ['label_id', 'labelset_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('labelset_association', schema=None) as batch_op:
        batch_op.drop_index('labelset_joint_idx')

    # ### end Alembic commands ###
