"""add labelset_id to model

Revision ID: a413c04cbe20
Revises: f57f9a462b47
Create Date: 2020-04-07 17:43:02.823459

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a413c04cbe20'
down_revision = 'f57f9a462b47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('models', schema=None) as batch_op:
        batch_op.add_column(sa.Column('labelset_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_models_labelset_id'), ['labelset_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_models_labelset_id_labelsets'), 'labelsets', ['labelset_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('models', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_models_labelset_id_labelsets'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_models_labelset_id'))
        batch_op.drop_column('labelset_id')

    # ### end Alembic commands ###
