"""add training_iters to model

Revision ID: aafc57349b5e
Revises: ce6e09db98ea
Create Date: 2019-10-28 16:23:30.073947

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aafc57349b5e'
down_revision = 'ce6e09db98ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('models', schema=None) as batch_op:
        batch_op.add_column(sa.Column('training_iters', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('models', schema=None) as batch_op:
        batch_op.drop_column('training_iters')

    # ### end Alembic commands ###
