"""add label scale and model optimize_scale

Revision ID: b2139b9c9532
Revises: f47aa0430601
Create Date: 2020-05-07 14:06:46.774057

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2139b9c9532'
down_revision = 'f47aa0430601'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('labels', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scale', sa.Float(), nullable=True))

    with op.batch_alter_table('models', schema=None) as batch_op:
        batch_op.add_column(sa.Column('optimize_scale', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('models', schema=None) as batch_op:
        batch_op.drop_column('optimize_scale')

    with op.batch_alter_table('labels', schema=None) as batch_op:
        batch_op.drop_column('scale')

    # ### end Alembic commands ###
