"""add global_scale to model

Revision ID: b2213ef935c6
Revises: aafc57349b5e
Create Date: 2019-10-29 12:17:56.512598

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2213ef935c6'
down_revision = 'aafc57349b5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('models', schema=None) as batch_op:
        batch_op.add_column(sa.Column('global_scale', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('models', schema=None) as batch_op:
        batch_op.drop_column('global_scale')

    # ### end Alembic commands ###
