"""move name to label_sources

Revision ID: b451280801d3
Revises: 48d666940917
Create Date: 2019-10-17 18:31:29.943838

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b451280801d3'
down_revision = '48d666940917'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dye_detectors', schema=None) as batch_op:
        batch_op.drop_constraint('uq_dye_detectors_name', type_='unique')
        batch_op.drop_column('name')

    with op.batch_alter_table('label_sources', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(), nullable=True))
        batch_op.create_unique_constraint(batch_op.f('uq_label_sources_name'), ['name'])

    with op.batch_alter_table('models', schema=None) as batch_op:
        batch_op.drop_constraint('uq_models_name', type_='unique')
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('models', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(), nullable=True))
        batch_op.create_unique_constraint('uq_models_name', ['name'])

    with op.batch_alter_table('label_sources', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_label_sources_name'), type_='unique')
        batch_op.drop_column('name')

    with op.batch_alter_table('dye_detectors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(), nullable=True))
        batch_op.create_unique_constraint('uq_dye_detectors_name', ['name'])

    # ### end Alembic commands ###
