"""create median_smoothers table

Revision ID: b9c9310283ce
Revises: 57e661471740
Create Date: 2020-04-30 03:17:46.531858

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9c9310283ce'
down_revision = '57e661471740'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('median_smoothers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kernel_size', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['smoothers.id'], name=op.f('fk_median_smoothers_id_smoothers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_median_smoothers'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('median_smoothers')
    # ### end Alembic commands ###
