"""add plots and roc_curves

Revision ID: c53914106486
Revises: 5d1ceba771b9
Create Date: 2019-10-22 15:52:24.094014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c53914106486'
down_revision = '5d1ceba771b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(), nullable=True),
    sa.Column('plot_type', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_plots'))
    )
    op.create_table('roc_curves',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('imageset_id', sa.Integer(), nullable=True),
    sa.Column('source_id_pred', sa.Integer(), nullable=True),
    sa.Column('source_id_gt', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['plots.id'], name=op.f('fk_roc_curves_id_plots')),
    sa.ForeignKeyConstraint(['imageset_id'], ['imagesets.id'], name=op.f('fk_roc_curves_imageset_id_imagesets')),
    sa.ForeignKeyConstraint(['source_id_gt'], ['label_sources.id'], name=op.f('fk_roc_curves_source_id_gt_label_sources')),
    sa.ForeignKeyConstraint(['source_id_pred'], ['label_sources.id'], name=op.f('fk_roc_curves_source_id_pred_label_sources')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roc_curves'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('roc_curves')
    op.drop_table('plots')
    # ### end Alembic commands ###
