"""add image_id x y to label

Revision ID: c68c6764ab57
Revises: 09e2d2845329
Create Date: 2019-09-25 18:53:45.169873

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c68c6764ab57'
down_revision = '09e2d2845329'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('labels', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('x', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('y', sa.Float(), nullable=True))
        batch_op.create_foreign_key('image_id', 'images', ['image_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('labels', schema=None) as batch_op:
        batch_op.drop_constraint('image_id', type_='foreignkey')
        batch_op.drop_column('y')
        batch_op.drop_column('x')
        batch_op.drop_column('image_id')

    # ### end Alembic commands ###
