"""add image_preproc_type

Revision ID: ce6e09db98ea
Revises: c53914106486
Create Date: 2019-10-27 15:58:47.059382

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce6e09db98ea'
down_revision = 'c53914106486'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('models', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_preproc_type', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('models', schema=None) as batch_op:
        batch_op.drop_column('image_preproc_type')

    # ### end Alembic commands ###
