"""add_landmark_color

Revision ID: d4fa38417b7a
Revises: 1cbb610785d5
Create Date: 2021-11-10 23:09:20.639803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4fa38417b7a'
down_revision = '1cbb610785d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('landmarks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('color', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('landmarks', schema=None) as batch_op:
        batch_op.drop_column('color')

    # ### end Alembic commands ###
