"""add model mirrored

Revision ID: f06629f6cad9
Revises: 585a7ba2387c
Create Date: 2020-11-03 01:07:29.233763

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f06629f6cad9'
down_revision = '585a7ba2387c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('models', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mirrored', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('models', schema=None) as batch_op:
        batch_op.drop_column('mirrored')

    # ### end Alembic commands ###
