"""add area and mean_value to labels

Revision ID: f47aa0430601
Revises: b9c9310283ce
Create Date: 2020-04-30 05:41:50.324873

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f47aa0430601'
down_revision = 'b9c9310283ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('labels', schema=None) as batch_op:
        batch_op.add_column(sa.Column('area', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('mean_value', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('labels', schema=None) as batch_op:
        batch_op.drop_column('mean_value')
        batch_op.drop_column('area')

    # ### end Alembic commands ###
