"""create labelsets

Revision ID: f57f9a462b47
Revises: efd0691aaf5e
Create Date: 2020-04-07 12:57:27.255206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f57f9a462b47'
down_revision = 'efd0691aaf5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('labelsets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_labelsets')),
    sa.UniqueConstraint('name', name=op.f('uq_labelsets_name'))
    )
    op.create_table('labelset_association',
    sa.Column('label_id', sa.Integer(), nullable=True),
    sa.Column('labelset_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['label_id'], ['labels.id'], name=op.f('fk_labelset_association_label_id_labels')),
    sa.ForeignKeyConstraint(['labelset_id'], ['labelsets.id'], name=op.f('fk_labelset_association_labelset_id_labelsets'))
    )
    with op.batch_alter_table('labelset_association', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_labelset_association_label_id'), ['label_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_labelset_association_labelset_id'), ['labelset_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('labelset_association', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_labelset_association_labelset_id'))
        batch_op.drop_index(batch_op.f('ix_labelset_association_label_id'))

    op.drop_table('labelset_association')
    op.drop_table('labelsets')
    # ### end Alembic commands ###
