"""added augment_bg to model

Revision ID: ff5dd5c51ca2
Revises: b2213ef935c6
Create Date: 2019-10-30 14:33:18.853295

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff5dd5c51ca2'
down_revision = 'b2213ef935c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('models', schema=None) as batch_op:
        batch_op.add_column(sa.Column('augment_bg', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('models', schema=None) as batch_op:
        batch_op.drop_column('augment_bg')

    # ### end Alembic commands ###
